#!/usr/bin/env bash
CONTAINER_NAME="grafana"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

containerId="$(docker ps --filter "name=${CONTAINER_NAME}" -q)"

if [ ! -z $containerId ]; then
	echo "Container '${CONTAINER_NAME}' is already running"
	exit 0
fi

containerId="$(docker ps --filter "name=${CONTAINER_NAME}" -aq)"

if [ ! -z $containerId ]; then
	echo "Container '${CONTAINER_NAME}' is already created. Start..."
	docker start $CONTAINER_NAME
	exit 0
fi

docker run -d --name $CONTAINER_NAME -p 3000:3000 grafana/grafana
