#!/usr/bin/env bash
CONTAINER_NAME="influxdb"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

containerId="$(docker ps --filter "name=${CONTAINER_NAME}" -q)"

if [ ! -z $containerId ]; then
	echo "Container '${CONTAINER_NAME}' is already running"
	exit 0
fi

containerId="$(docker ps --filter "name=${CONTAINER_NAME}" -aq)"

if [ ! -z $containerId ]; then
	echo "Container '${CONTAINER_NAME}' is already created. Start..."
	docker start $CONTAINER_NAME
	exit 0
fi

docker run -p 8086:8086 -d \
	-v $DIR/data:/var/lib/influxdb \
	-v $DIR/influxdb.conf:/etc/influxdb/influxdb.conf:ro \
	--name $CONTAINER_NAME \
	influxdb
