#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

docker run \
    -v $DIR:/var/loadtest \
    --net host \
    --entrypoint /bin/bash \
    -it my-image-nodejs
# --name tank \
# -it my-tank
# -it direvius/yandex-tank /bin/bash
